title: My DSA Progress
author: Anni Mukherjee
description: A documentation of my journey through Data Structures and Algorithms.
baseurl: "/dsa" # The name of your repository
url: "https://annimukherjee.github.io" # Your GitHub Pages URL