# .github/workflows/dsa-tracker.yml
name: DSA Problem Tracker

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  update-tracker:
    if: "!contains(github.event.head_commit.message, '[skip tracker]')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install deps (once)
        run: npm ci
        working-directory: .github/tracker/scripts   # package.json lives here

      - name: Update tracker data/website
        run: |
          node .github/tracker/scripts/update-tracker.mjs \
            "$GITHUB_SHA" "$GITHUB_EVENT_BEFORE"

