# .github/workflows/pages.yml
name: Deploy GitHub Pages

on:
  workflow_run:
    workflows: ["DSA Problem Tracker"]
    types: 
      - completed
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency: 
      group: pages
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: '.github/tracker'
      - id: deployment
        uses: actions/deploy-pages@v4