name: Deploy GitHub PagesMore actions

on:
  push:
    branches: [ main, master ]

  workflow_dispatch:
  workflow_run:
    workflows: ["DSA Problem Tracker"]
    types:
      - completed

# Sets permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
More actions
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.github/tracker'

      - name: Deploy to GitHub Pages
        id: deployment